// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvuklnrtagwivkcznedy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2dWtsbnJ0YWd3aXZrY3puZWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2NDkwNTIsImV4cCI6MjA3NjIyNTA1Mn0.r9fUkt6Ny5wEfYfWFjyFsT2_-sfrQHzGElcIf64O4hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});